#!/bin/bash
OUTPUT="$1"
MAX_RETRIES=5
RETRY_DELAY=5
RETRY_COUNT=0

docker-compose up --build -d

sleep $RETRY_DELAY

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker cp docker-deployment:/deployment "$OUTPUT"; then
        chmod u+x "$OUTPUT"/deployment
        ./ci/deployment --help
        echo "Build successful"
        break  # Exit the loop on success
    else
        echo "Build failed, retrying..."
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep $RETRY_DELAY
    fi
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo "Max retries reached, build failed"
fi

docker-compose down


