imageName: storage-api
imageTag: latest
containerName: storage-api
temple: "/opt/deployment/deployment.mustache"
uploadUrl: https://docker-registry.com/upload
dockerRegistryDomain: docker-registry.com
dockerfile: .
bind:
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - example_logs:/opt/logs
    - "/var/www:/var/www"
    - "/var/log:/var/log"
limit:
  memory: 1024M
  cpu: 0.5
volumes:
  - example_logs: