version: "3.7"

services:
  docker-deployment:
    container_name: docker-deployment
    image: docker-deployment
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build/:/build/
    deploy:
      resources:
        limits:
          memory: 256M
