version: '3.7'

services:
    {{.IMAGE_NAME}}:
      image: {{.IMAGE_NAME}}:{{.IMAGE_TAG}}
      container_name: {{.IMAGE_NAME}}
      restart: always
      deploy:
        resources:
          limits:
            cpus: "{{.CPU_LIMIT}}"
            memory: "{{.MEMORY_LIMIT}}"
      ports:
        {{range .BIND_CONTAINER_PORT}}- "{{.}}"
        {{end}}
      volumes:
        {{range .BIND_VOLUMES}}- {{.}}
        {{end}}
  { { if .VOLUMES } }
volumes:
    {{range .VOLUMES}}  {{.}}:
      {{end}}
  { { end } }